### ISSUE TITLE
AttributeError: 'WikiaPage' object has no attribute 'references'

### ISSUE THREAD

**Issue by ClementJ18** [Timidger/Wikia#15]
### Code
```
import wikia
wiki = "edain"
article = "Mordor"
article = wikia.page(wiki, article, preload=True)
```
### Expected Result
Sucessfully loading the Mordor page from the wiki

### Actual Result
Traceback
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36\lib\site-packages\wikia\wikia.py", line 185, in page
    return WikiaPage(sub_wikia, title, redirect=redirect, preload=preload)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36\lib\site-packages\wikia\wikia.py", line 216, in __init__
    getattr(self, prop)
AttributeError: 'WikiaPage' object has no attribute 'references'
```

**Comment by Timidger** [comment]
Looks to be an easy fix, just need to remove references and links from [this line](https://github.com/Timidger/Wikia/blob/master/wikia/wikia.py#L215). I'll try to get to this later, but patches welcome.

**Comment by Timidger** [comment]
A 1.4.4 has been released on pypi with this fixed
